name: ci


on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Node Version Check 
        run: node --version 
  train-model:
    name: GPU-test 
    runs-on: gpu-2-core-ubuntu-2204
    steps:
      - uses: actions/checkout@v3

      - name: Check GPU
        run: nvidia-smi

